apiVersion: v1
kind: Service
metadata:
  name: flask-web-svc
spec:
  selector:
    app: flask-web
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
  #type: ClusterIP # to make it work with my nginx ingress