apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: {{ .Values.db.username | required "database username required" | b64enc | quote }}
 password: {{ .Values.db.password | required "database password required" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: {{ .Values.db.rootpassword | required "database root password required" | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
 host: {{ .Values.db.host}}
 name: {{ .Values.db.db_name}}