FROM python:3.9-slim

WORKDIR /app

COPY /ant_cli/ /app
COPY /models /app/models
COPY /requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

# Ensure the CLI script is executable
RUN chmod +x ants_cli.py

# Set the entrypoint to the CLI script
ENTRYPOINT ["python", "ants_cli.py"]

