# Apply secrets separately from the Helm chart to avoid using Vault or applying plain text passwords.
# Obviously, do not use this method in production.
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
data:
  username: b3Jlbg==
  password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: b3Jlbg==
 password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: cm9vdG9yZW4=