FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pwd
RUN ls 

#COPY . .
COPY /flask/ /app
COPY /models /app/models

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the Flask app
CMD ["python", "flaskapi.py"]

# From the root dir
# docker build -t flaskapiant:0.0.1 -f flask\dockerfile .